### ISSUE TITLE
Кастомные tpl для страниц

### ISSUE THREAD

**Issue by pulse-studio** [SimplaCMS-PRO/Simpla#17]
https://github.com/SimplaCMS-PRO/Simpla/blob/master/view/PageView.php#L32

Может более элегантное решение, выбор tpl в админ панели или ручной ввод названия шаблона?

что если у нас есть 5 из 20 страниц со схожим дизайном, но разным урл, будем дублировать tpl?
А если потом надо будет поменять дизайн в этих tpl)?

**Comment by osben** [comment]
данное решение не затрагивает изменение в БД. Пока что не хочется вносить изменение в БД.
